version: "3.8"
services:
  nginx:
    image: nginx
    build: ./nginx/
    # restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - dist:/etc/nginx/html/
    depends_on:
      - api
      - app
    networks:
      - "api.network"
  api:
    image: shiftingphotons/moodytags:latest
    command: bundle exec hanami server --host=0.0.0.0 --port=8000
    env_file:
      - .env.production
    networks:
      - "api.network"
    depends_on:
      - db
  app:
    image: shiftingphotons/moodytags-client:latest
    networks:
      - "api.network"
    volumes:
      - dist:/app/dist
  db:
    image: postgres:12
    env_file:
      - .env.production
    networks:
      - "api.network"

volumes:
  dist:

networks:
  api.network:
