version: "3.8"
networks:
  api.network:
volumes:
  dist:

services:
  api:
    build: .
    command: bundle exec hanami server --host=0.0.0.0 --port=8000
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    networks:
      - "api.network"
  db:
    image: postgres:12
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=moody_tags
      - POSTGRES_PASSWORD=moody_tags
      - POSTGRES_DB=moody_tags_development
    networks:
      - "api.network"
