name: Reviewdog

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: rubocop
      uses: reviewdog/action-rubocop@v1
      with:
        rubocop_extensions: rubocop-performance rubocop-rspec rubocop-sequel
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review

    - name: reek
      uses: reviewdog/action-reek@v1
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
